// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZ_YoeqYmxxM-h5rkdhBVfHreZGnm8zE',
    appId: '1:127878788563:web:b1fc293aed4f6f1de96b26',
    messagingSenderId: '127878788563',
    projectId: 'renter-pay-a2136',
    authDomain: 'renter-pay-a2136.firebaseapp.com',
    storageBucket: 'renter-pay-a2136.firebasestorage.app',
    measurementId: 'G-E557GZ24F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NR5UfKLMiRVEbhIA6Oq9OSewVZTr7QY',
    appId: '1:127878788563:android:238fa1e02c043fb1e96b26',
    messagingSenderId: '127878788563',
    projectId: 'renter-pay-a2136',
    storageBucket: 'renter-pay-a2136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWldnjhScH7-p9gwnU_0DzjkT65wCgPH8',
    appId: '1:127878788563:ios:26db349eacc04d20e96b26',
    messagingSenderId: '127878788563',
    projectId: 'renter-pay-a2136',
    storageBucket: 'renter-pay-a2136.firebasestorage.app',
    iosBundleId: 'com.renter.pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWldnjhScH7-p9gwnU_0DzjkT65wCgPH8',
    appId: '1:127878788563:ios:d28dc36a0c0b6c37e96b26',
    messagingSenderId: '127878788563',
    projectId: 'renter-pay-a2136',
    storageBucket: 'renter-pay-a2136.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZ_YoeqYmxxM-h5rkdhBVfHreZGnm8zE',
    appId: '1:127878788563:web:78e47e9c612fe849e96b26',
    messagingSenderId: '127878788563',
    projectId: 'renter-pay-a2136',
    authDomain: 'renter-pay-a2136.firebaseapp.com',
    storageBucket: 'renter-pay-a2136.firebasestorage.app',
    measurementId: 'G-V65TTT16SD',
  );
}
