// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6f-GxJPGxjTl9UyirfKjVOBK0ohobYbk',
    appId: '1:945407931386:android:1007c21c9d0b1ea6e4ea43',
    messagingSenderId: '945407931386',
    projectId: 'renter-pay',
    storageBucket: 'renter-pay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_2e_3bYGYPzTw50VnLI1dYgMtrfnsIY',
    appId: '1:945407931386:ios:23d7f496d9621329e4ea43',
    messagingSenderId: '945407931386',
    projectId: 'renter-pay',
    storageBucket: 'renter-pay.firebasestorage.app',
    androidClientId: '945407931386-ok4jok83iupl9n28o5ib80vgf101128g.apps.googleusercontent.com',
    iosClientId: '945407931386-1cmu4fu4mc30tlo6k8osfoods747dt53.apps.googleusercontent.com',
    iosBundleId: 'com.renter.pay',
  );
}
